language: java
jdk: oraclejdk8

# need for docker daemon
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
  - master
  - develop
  - "/^feature.*$/"

script: mvn clean verify org.eluder.coveralls:coveralls-maven-plugin:report

notifications:
  slack:
    secure: t/w3K9ZvPaRZ6cl/dDd7TGdpmWbIHyXAYWiRIork7DccotPqI95556PTCJSuomOPwzwjZYrJpWfOZhtskwTBtvhXHnUT2nHtmyBzBPeI+03i8cXrrhEECrxy42hvnooqIPS7NzlpVKvq2BMNlJMTpVAJVXH2yQH997Wyj7X0NVQZAcDDfs9tDSlqPAMkpuHBLHtIpIwmFbQOjOVxUx5EGaqeBnGFY0gMNlmqWeLQ1jFMzyKBVwSjP5lOtMURqsHHFa/quD3qCuXD1kpXNDTmfG7FM23HnmdxjxuSg/shUmDVdGrTAL623Jy553kDGzARbyxLlqAIVeGVEPTu1886125Y+tsdiQkWbWSh63IgkoJzTrdlZMnuBz6MqvSe4ckMtbogWrp9Dcol7h7uK0QPIRhrfsDOpElGuZpJhzS9JCRX0sDRH7QLvNzdGMSBTSfzqvAs0OqZf5ZZAMyQryo5/iG/e7q5ZOZQgNp+lAyosXeDo98D4RVwr5FTl92SjisZN49TO4nWrz78prgTWfvuUJ5FnAaVx/IR/p8I6znTU7NNXAigzcc48HUufXqW6bxgAxmrYGNJ0ZV27KRhPJ9jg9g0pQIjmCHZrcRWdcCC8M+tefoN1xdiKp6lr/CrB+oxifKWtcjZ1xIpic3WV0MkJp3gnzNJ8+nP9WQo6LSudnQ=
    on_success: change
    on_failure: always
