--
-- EPG Meta info table
--
CREATE TABLE epg_meta (
  name VARCHAR(255) NOT NULL PRIMARY KEY,
  created TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(255) NOT NULL,
  graphs VARCHAR NOT NULL,
  vertices VARCHAR NOT NULL,
  edges VARCHAR NOT NULL
);
