---
version: '3.4'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - net
    healthcheck:
      # yellow (under replicated - which can happen for single node) and green status is considered healthy
      test: ["CMD-SHELL", "curl -fs 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s&filter_path=status' | grep -qE '(green|yellow)' || exit 1"]
      interval: 1m
      timeout: 60s
      retries: 3
      start_period: 30s

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - net
    depends_on:
      - elasticsearch

  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - net

  adminer:
    image: adminer
    restart: always
    ports:
        - 9090:8080
    networks:
      - net

networks:
  net:
    driver: bridge