---
spring:
  profiles:
    include:
      - h2

  datasource:
    url: jdbc:h2:/opt/var/stellar-search/docker;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false

  h2.console.enabled: true
  security.enabled: false

logging:
  level:
    au.com.d2dcrc: DEBUG

security.basic.enabled: false
management.security.enabled: false

elasticsearch.rest-client:
  addresses:
    - elasticsearch:9200
