---
logging:
  level:
    root: INFO
    au.com.d2dcrc: DEBUG

spring:
  profiles:
    include:
      - h2

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false

  main:
    # we don't want the banner shown for each test
    banner-mode: "off"  # quoted since this is not a boolean but an enum (console, log, off)

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate

# turn off authentication for actuator
security.basic.enabled: false
spring.security.enabled: false
management.security.enabled: false
