---
logging:
  level:
    au.com.d2dcrc: DEBUG

spring:
  profiles:
    include:
      - h2

  datasource:
    # DB_CLOSE_ON_EXIT=FALSE is required to allow services to release claims on shutdown.
    # Don't set this property in test profiles, as it prevents integrations tests from clearing the database between tests
    url: jdbc:h2:./develop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
  h2.console.enabled: true

# needed for /h2-console
security.basic.enabled: false
# turn off authentication for actuator
spring.security.enabled: false
management.security.enabled: false
