---
jwt:
  secret: !!binary |
    m1VpQoYOiEtnF35S9Hpc6eS/r701SDIvOUpCQ8qhNgCv/hiic962GsUgX3YACtW+
    O5j+xSrabRzvE4j19UuK0rIpaJsgmeoQh4/F2AcstekfSiEqAqKv/tVgWocX91jE
    qid4TJYez9dIv4ZF4UPvOe3HxrlSwxRw5mzNpaB+2OGTMNhoO3ngk/ZQ1EMpXbp1
    zjxxcOQMTLPDTxK26O9FldNm+wpCku4/4/PmCLjFVml2MIdVT1SUvvFscdZsrmEu
    PSVF9uIPw8JI+6mc5AzGUyLcHXEtWv1LcvS3Cy3WU6VZfvLqQjujtP1O7xY0QTAG
    p20hmWDCu7J+TCWNDxgoEA==
